function json = perfresults2json(results)

context.date = datetime('now');
context.host_name = results(1).Samples.Host(1);
%c.executable = 'MATLAB';
%c.num_cpus = NaN;
%c.mhz_per_cpu = NaN;
%c.cpu_scaling_enabled = false;
%c.caches = NaN;

benchmarks = arrayfun(@(r) struct(...
    "name", r.Name, ...
    "iterations", 1, ...
    "real_time", median(r.Samples.MeasuredTime), ...
    "cpu_time", min(r.Samples.MeasuredTime), ...
    "time_unit", "s", ...
    "threads", 1), ...
    results);

s.context = context;
s.benchmarks = benchmarks;
json = jsonencode(s);
