function json = perfresults2pybenchjson(results)
machine_info.node = matlab.unittest.internal.getHostname;

commit_info.id = "unversioned";
commit_info.time = NaT;
commit_info.author_time = NaT;
commit_info.dirty = false;

if ~isempty(matlab.project.currentProject)
    commit_info.project = currentProject;
else
    commit_info.project = "";
end

commit_info.branch = "(unknown)";


benchmarks = arrayfun(@(r) struct(...
    "group", missing,...
    "name", r.Name, ...
    "fullname", string(r.TestActivity.TestResult(1).TestElement.BaseFolder) + filesep + r.Name, ...
    "params", missing, ...
    "param", missing, ...
    "extra_info", struct, ...
    "options", struct(...
        "disable_gc", false, ...
        "timer", "tic", ...
        "min_rounds", 4, ...
        "max_time", Inf, ...
        "min_time", r.CalibrationValue, ...
        "warmup", true), ...
    "stats", struct(...
        "min", min(r.Samples.MeasuredTime), ...
        "max", max(r.Samples.MeasuredTime), ...
        "mean", mean(r.Samples.MeasuredTime), ...
        "stddev", std(r.Samples.MeasuredTime), ...
        "rounds", numel(r.Samples.MeasuredTime), ...
        "median", median(r.Samples.MeasuredTime), ...
        "iqr", iqr(r.Samples.MeasuredTime), ...
        "q1", quantile(r.Samples.MeasuredTime, .25), ...
        "q3", quantile(r.Samples.MeasuredTime, .75), ...
        "iqr_outliers", nnz(...
            r.Samples.MeasuredTime > mean(r.Samples.MeasuredTime) + (iqr(r.Samples.MeasuredTime)/2) | ...
            r.Samples.MeasuredTime < mean(r.Samples.MeasuredTime) - (iqr(r.Samples.MeasuredTime)/2)), ...
        "stddev_outliers", nnz(...
            r.Samples.MeasuredTime > mean(r.Samples.MeasuredTime) + std(r.Samples.MeasuredTime) | ...
            r.Samples.MeasuredTime < mean(r.Samples.MeasuredTime) - std(r.Samples.MeasuredTime)), ...
        "outliers", nnz(...
            r.Samples.MeasuredTime > mean(r.Samples.MeasuredTime) + (iqr(r.Samples.MeasuredTime)/2) | ...
            r.Samples.MeasuredTime < mean(r.Samples.MeasuredTime) - (iqr(r.Samples.MeasuredTime)/2)) + ...
            ";" + ...
            nnz(...
            r.Samples.MeasuredTime > mean(r.Samples.MeasuredTime) + std(r.Samples.MeasuredTime) | ...
            r.Samples.MeasuredTime < mean(r.Samples.MeasuredTime) - std(r.Samples.MeasuredTime)), ...
        "ld15iqr", NaN, ...
        "hd15iqr", NaN, ...
        "ops", numel(r.Samples.MeasuredTime)/sum(r.Samples.MeasuredTime), ...
        "total", sum(r.Samples.MeasuredTime), ...
        "iterations", 1)...
    ) ...
, results);
            
s.machine_info = machine_info;
s.commit_info = commit_info;
s.benchmarks = benchmarks;
s.datetime = datetime("now");
s.version = "";

json = jsonencode(s);
